import Footer from "@/components/Footer";
import Header from "@/components/Header";

const TermAndCondition = () => {
  return (
    <>
      <Header />

      <div className="min-h-screen px-4 sm:px-6 md:px-8 lg:px-12 xl:px-20 py-8 md:py-10  bg-white mb-10">
        {/* Header */}

        <div className=" bg-white rounded-xl shadow-sm border border-gray-200 p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:border-green-300">
          <div className="bg-white border-b border-gray-200 py-8 px-4">
            <div className="max-w-5xl mx-auto flex flex-col sm:flex-row sm:justify-between sm:items-start gap-2">
              <div>
                <h1 className="text-2xl md:text-3xl font-bold text-green-800">
                  Terms & Conditions
                </h1>
              </div>
              <p className="text-sm text-gray-500">
                Last Updated: [DD/MM/YYYY]
              </p>
            </div>
            <div className="max-w-5xl mx-auto mt-3">
              <p className="text-gray-600 text-sm md:text-base">
                This document is an electronic record in terms of the
                Information Technology Act, 2000 and rules thereunder. This
                electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </p>
              <p className="text-gray-600 text-sm md:text-base mt-2">
                Published in accordance with the Information Technology
                (Intermediaries Guidelines) Rules, 2011.
              </p>
              <p className="text-gray-600 text-sm md:text-base mt-1">
                Website:{" "}
                <a
                  href="https://rajlakshmijaviks.com"
                  className="text-green-700 underline"
                >
                  https://rajlakshmijaviks.com
                </a>
              </p>
              <p className="text-gray-600 text-sm md:text-base mt-1">
                Owned and operated by Rajlakshmijaviks International, Indore,
                Madhya Pradesh, India.
              </p>
            </div>
          </div>

          <div className="max-w-5xl mx-auto px-4 py-10">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
              {/* Left Column */}
              <div className="lg:col-span-2 space-y-10">
                {/* Terms of Use */}
                <section>
                  <h2 className="text-xl md:text-2xl font-bold text-green-800 mb-4">
                    Terms of Use
                  </h2>
                  <ul className="list-disc list-inside text-gray-600 text-sm space-y-2 ml-2">
                    <li>
                      Your access to and use of the website constitutes your
                      agreement to these Terms & Conditions.
                    </li>
                    <li>
                      You agree to provide true, accurate, and complete
                      information during registration or purchase.
                    </li>
                    <li>
                      All services are used at your own discretion and risk.
                    </li>
                    <li>
                      We reserve the right to modify or discontinue services
                      without prior notice.
                    </li>
                  </ul>
                </section>

                {/* User Responsibilities */}
                <section>
                  <h2 className="text-xl md:text-2xl font-bold text-green-800 mb-4">
                    User Responsibilities
                  </h2>
                  <ul className="list-disc list-inside text-gray-600 text-sm space-y-2 ml-2">
                    <li>
                      You agree to pay all applicable charges for products or
                      services purchased.
                    </li>
                    <li>
                      You shall not use the platform for any unlawful, illegal,
                      or prohibited activities.
                    </li>
                    <li>
                      You agree to indemnify and hold harmless Rajlakshmijaviks
                      International from any claims, damages, or liabilities
                      arising from misuse of the platform.
                    </li>
                  </ul>
                </section>

                {/* Legal Jurisdiction */}
                <section>
                  <h2 className="text-xl md:text-2xl font-bold text-green-800 mb-4">
                    Legal Jurisdiction
                  </h2>
                  <ul className="list-disc list-inside text-gray-600 text-sm space-y-2 ml-2">
                    <li>
                      These Terms shall be governed by and construed in
                      accordance with the laws of India.
                    </li>
                    <li>
                      Any disputes shall be subject to the exclusive
                      jurisdiction of the courts in Indore, Madhya Pradesh.
                    </li>
                    <li>
                      We shall not be liable for any delay or failure due to
                      force majeure events beyond our control.
                    </li>
                  </ul>
                </section>

                {/* Intellectual Property Rights */}
                <section>
                  <h2 className="text-xl md:text-2xl font-bold text-green-800 mb-4">
                    Intellectual Property Rights
                  </h2>
                  <p className="text-gray-600 text-sm mb-2">
                    All content, including text, graphics, logos, images, and
                    software, is the property of Rajlakshmijaviks International.
                  </p>
                  <p className="text-gray-600 text-sm">
                    Unauthorized reproduction, distribution, or use of any
                    content is strictly prohibited.
                  </p>
                </section>

                {/* Third Party Links */}
                <section>
                  <h2 className="text-xl md:text-2xl font-bold text-green-800 mb-4">
                    Third Party Links
                  </h2>
                  <p className="text-gray-600 text-sm">
                    Our website may contain links to third-party websites. These
                    websites are governed by their own terms and privacy
                    policies. We are not responsible for the content or
                    practices of such third-party sites.
                  </p>
                </section>
              </div>

              {/* Right Column - Sticky Cards */}
              <div className="space-y-6 lg:sticky lg:top-8 lg:self-start">
                {/* Contact Information */}
                <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
                  <h3 className="text-lg font-bold text-green-800 mb-3">
                    Contact Information
                  </h3>
                  <p className="text-gray-600 text-sm mb-3">
                    For any queries, complaints, or concerns regarding these
                    Terms & Conditions, please contact us:
                  </p>
                  <ul className="text-gray-600 text-sm space-y-2">
                    <li className="flex items-start gap-2">
                      <span className="text-green-600 mt-0.5">•</span>
                      <span>Email: support@rajlakshmijaviks.com</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-green-600 mt-0.5">•</span>
                      <span>Address: Indore, Madhya Pradesh, India</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-green-600 mt-0.5">•</span>
                      <span>Phone: +91 12345678</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default TermAndCondition;
