
import FAQSection from "@/components/FAQSection";
import Seo from "@/components/Seo";

const TermAndCondition = () => {
  return (
    <>
      <Seo 
        title="Terms & Conditions | Rajlakshmi Javiks International"
        description="Terms and conditions for using the Rajlakshmi Javiks International website and services."
        url="/terms"
      />
      <div className="min-h-screen px-4 sm:px-6 md:px-8 lg:px-12 xl:px-20 py-8 md:py-10  bg-white mb-10">
        {/* Header */}

        <div className=" bg-white rounded-xl shadow-sm border border-gray-200 p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:border-green-300">
          <div className="bg-white border-b border-gray-200 py-8 px-4">
            <div className="max-w-5xl mx-auto flex flex-col sm:flex-row sm:justify-between sm:items-start gap-2">
              <div>
                <h1 className="text-2xl md:text-3xl font-bold text-green-800">
                  Terms & Conditions
                </h1>
              </div>

            </div>
            <div className="max-w-5xl mx-auto mt-3">
              <p className="text-gray-600 text-sm md:text-base">
                This document is an electronic record in terms of the
                Information Technology Act, 2000 and rules thereunder. This
                electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </p>
              <p className="text-gray-600 text-sm md:text-base mt-2">
                Published in accordance with the Information Technology
                (Intermediaries Guidelines) Rules, 2011.
              </p>
              <p className="text-gray-600 text-sm md:text-base mt-1">
                Website:{" "}
                <a
                  href="https://rajlakshmijaviks.com"
                  className="text-green-700 underline"
                >
                  https://rajlakshmijaviks.com
                </a>
              </p>
              <p className="text-gray-600 text-sm md:text-base mt-1">
                Owned and operated by Rajlakshmijaviks International, Indore,
                Madhya Pradesh, India.
              </p>
            </div>
          </div>

          <div className="max-w-5xl mx-auto px-4 py-10">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
              {/* Left Column */}
              <div className="lg:col-span-2 space-y-10">
                {/* Terms of Use */}
                <section>
                  <h2 className="text-xl md:text-2xl font-bold text-green-800 mb-4">
                    Terms of Use
                  </h2>
                  <ul className="list-disc list-inside text-gray-600 text-sm space-y-2 ml-2">
                    <li>
                      Your access to and use of the website constitutes your
                      agreement to these Terms & Conditions.
                    </li>
                    <li>
                      You agree to provide true, accurate, and complete
                      information during registration or purchase.
                    </li>
                    <li>
                      All services are used at your own discretion and risk.
                    </li>
                    <li>
                      We reserve the right to modify or discontinue services
                      without prior notice.
                    </li>
                  </ul>
                </section>

                {/* User Responsibilities */}
                <section>
                  <h2 className="text-xl md:text-2xl font-bold text-green-800 mb-4">
                    User Responsibilities
                  </h2>
                  <ul className="list-disc list-inside text-gray-600 text-sm space-y-2 ml-2">
                    <li>
                      You agree to pay all applicable charges for products or
                      services purchased.
                    </li>
                    <li>
                      You shall not use the platform for any unlawful, illegal,
                      or prohibited activities.
                    </li>
                    <li>
                      You agree to indemnify and hold harmless Rajlakshmijaviks
                      International from any claims, damages, or liabilities
                      arising from misuse of the platform.
                    </li>
                  </ul>
                </section>

                {/* Legal Jurisdiction */}
                <section>
                  <h2 className="text-xl md:text-2xl font-bold text-green-800 mb-4">
                    Legal Jurisdiction
                  </h2>
                  <ul className="list-disc list-inside text-gray-600 text-sm space-y-2 ml-2">
                    <li>
                      These Terms shall be governed by and construed in
                      accordance with the laws of India.
                    </li>
                    <li>
                      Any disputes shall be subject to the exclusive
                      jurisdiction of the courts in Indore, Madhya Pradesh.
                    </li>
                    <li>
                      We shall not be liable for any delay or failure due to
                      force majeure events beyond our control.
                    </li>
                  </ul>
                </section>

                {/* Intellectual Property Rights */}
                <section>
                  <h2 className="text-xl md:text-2xl font-bold text-green-800 mb-4">
                    Intellectual Property Rights
                  </h2>
                  <p className="text-gray-600 text-sm mb-2">
                    All content, including text, graphics, logos, images, and
                    software, is the property of Rajlakshmijaviks International.
                  </p>
                  <p className="text-gray-600 text-sm">
                    Unauthorized reproduction, distribution, or use of any
                    content is strictly prohibited.
                  </p>
                </section>

                {/* Third Party Links */}
                <section>
                  <h2 className="text-xl md:text-2xl font-bold text-green-800 mb-4">
                    Third Party Links
                  </h2>
                  <p className="text-gray-600 text-sm">
                    Our website may contain links to third-party websites. These
                    websites are governed by their own terms and privacy
                    policies. We are not responsible for the content or
                    practices of such third-party sites.
                  </p>
                </section>
              </div>

              {/* Right Column - Sticky Cards */}
              <div className="space-y-6 lg:sticky lg:top-8 lg:self-start">
                {/* Contact Information */}
                <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
                  <h3 className="text-lg font-bold text-green-800 mb-3">
                    Contact Information
                  </h3>
                  <p className="text-gray-600 text-sm mb-3">
                    For any queries, complaints, or concerns regarding these
                    Terms & Conditions, please contact us:
                  </p>
                  <ul className="text-gray-600 text-sm space-y-2">
                    <li className="flex items-start gap-2">
                      <span className="text-green-600 mt-0.5">•</span>
                      <span>Email: contact@rajlakshmijaviks.com</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-green-600 mt-0.5">•</span>
                      <span>Address: 11, Manish Bag Colony Rd, Durga Nagar, Agarwal Nagar, Old Agarwal Nagar, Indore, Madhya Pradesh 452001</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-green-600 mt-0.5">•</span>
                      <span>Phone: +91 8769215905</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <FAQSection
        title="Terms & Conditions – Frequently Asked Questions"
        faqs={[
          {
            question: "What happens if I violate the Terms & Conditions?",
            answer: "If you violate our Terms & Conditions, we reserve the right to restrict or terminate your access to our website and services without prior notice.",
          },
          {
            question: "Can Rajlakshmi Javiks change these Terms & Conditions?",
            answer: "Yes, we reserve the right to modify or update these Terms & Conditions at any time. Changes will be effective immediately upon posting on the website. Continued use of our website after changes constitutes acceptance of the updated terms.",
          },
          {
            question: "Which courts have jurisdiction over disputes?",
            answer: "All disputes arising from these Terms & Conditions shall be subject to the exclusive jurisdiction of the courts in Indore, Madhya Pradesh 452001.",
          },
          {
            question: "Can I use content from Rajlakshmi Javiks website?",
            answer: "No, all content on our website including text, graphics, logos, images, and software is the intellectual property of Rajlakshmijaviks International. Unauthorized reproduction, distribution, or use is strictly prohibited.",
          },
          {
            question: "Is my payment information safe on your website?",
            answer: "Yes, we use secure payment gateways and do not store your card details on our servers. All transactions are processed through encrypted, PCI-compliant payment systems.",
          },
          {
            question: "What are my responsibilities as a user?",
            answer: "As a user, you agree to provide accurate information during registration, pay all applicable charges, refrain from unlawful activities on the platform, and indemnify Rajlakshmijaviks International from any claims arising from misuse.",
          },
        ]}
      />
    </>
  );
};

export default TermAndCondition;
